version: '3.7'

services:
  binance-bot:
    container_name: binance-bot
    image: chrisleekr/binance-trading-bot:latest
    networks:
      - internal
    env_file:
      - .env
    restart: unless-stopped
    environment:
      # - BINANCE_MODE=test
      - BINANCE_MODE=live
      - BINANCE_JOBS_ALIVE_ENABLED=true
      - BINANCE_JOBS_TRAILING_TRADE_ENABLED=true
      - BINANCE_JOBS_TRAILING_TRADE_SYMBOLS=["DEGOUSDT", "ALICEUSDT", "LINAUSDT", "PERPUSDT", "RAMPUSDT", "CFXUSDT", "EPSUSDT", "AUTOUSDT", "TKOUSDT", "PUNDIXUSDT", "TLMUSDT", "BTGUSDT", "MIRUSDT", "BARUSDT", "FORTHUSDT", "BAKEUSDT", "BURGERUSDT", "SLPUSDT", "SHIBUSDT", "ICPUSDT", "USDTGYEN", "ARUSDT", "POLSUSDT", "MDXUSDT", "MASKUSDT", "LPTUSDT", "NUUSDT", "XVGUSDT", "ATAUSDT", "GTCUSDT", "TORNUSDT", "KEEPUSDT", "ERNUSDT", "KLAYUSDT", "PHAUSDT", "BONDUSDT", "MLNUSDT", "DEXEUSDT", "C98USDT"]
      - BINANCE_JOBS_TRAILING_TRADE_CANDLES_INTERVAL=5m
      - BINANCE_JOBS_TRAILING_TRADE_CANDLES_LIMIT=10
      - BINANCE_JOBS_TRAILING_TRADE_BUY_TRIGGER_PERCENTAGE=1.00
      - BINANCE_JOBS_TRAILING_TRADE_BUY_STOP_PERCENTAGE=1.012
      - BINANCE_JOBS_TRAILING_TRADE_BUY_LIMIT_PERCENTAGE=1.0121
      - BINANCE_JOBS_TRAILING_TRADE_SELL_TRIGGER_PERCENTAGE=1.04
      - BINANCE_JOBS_TRAILING_TRADE_SELL_STOP_PERCENTAGE=0.99
      - BINANCE_JOBS_TRAILING_TRADE_SELL_LIMIT_PERCENTAGE=0.989
      - BINANCE_REDIS_HOST=binance-redis
      - BINANCE_REDIS_PORT=6379
      - BINANCE_REDIS_PASSWORD=secretp422
    ports:
      - 8080:80
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'

  binance-redis:
    container_name: binance-redis
    image: redis:6.2
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - internal
    restart: unless-stopped
    ports:
      - 53799:6379
    volumes:
      - redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      redis-server /usr/local/etc/redis/redis.conf --requirepass secretp422

  binance-mongo:
    container_name: binance-mongo
    image: mongo:3.2.20-jessie
    restart: unless-stopped
    ports:
      - 8081:27017
    networks:
      - internal
    volumes:
      - mongo_data:/data/db

networks:
  internal:
    driver: bridge
    # driver_opts:
    #     com.docker.network.driver.mtu: 1442

volumes:
  redis_data:
  mongo_data:
